spring:
  datasource:
    url: jdbc:mysql://localhost:3306/official_admin?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true

logging:
  level:
    com.company.admin: DEBUG
